site:
  title: DailyStandApp Documentation
  url: https://jug-da.github.io/DailyStandApp-MCP
  start_page: daily-standapp::index.adoc

content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs/src/docs
    - url: ../
      branches: develop
      start_path: docs

antora:
  extensions:
    - ./lib/mermaid-extension.js

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''

output:
  dir: ./_public
